import { ModeToggle } from "@/components/global/mode-toggle";
import { ThemeProvider } from "@/lib/providers/next-theme-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "CityGraph Viz",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
					<ModeToggle />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
